db_uri: mongodb://__MONGO_HOST__/open5gs

logger:
  file:
    path: /var/log/open5gs/bsf.log
  level: info

bsf:
  sbi:
    server:
      - address: __CP_IP__
        port: 7787
    client:
      scp:
        - uri: http://__CP_IP__:7778
