logger:
  file:
    path: /var/log/open5gs/nssf.log
  level: info

nssf:
  sbi:
    server:
      - address: __CP_IP__
        port: 7783
    client:
      scp:
        - uri: http://__CP_IP__:7778
      nsi:
        - uri: http://__CP_IP__:7777
          s_nssai:
            sst: 3
            sd: 198153
