db_uri: mongodb://__MONGO_HOST__/open5gs

logger:
  file:
    path: /var/log/open5gs/pcf.log
  level: info

pcf:
  sbi:
    server:
      - address: __CP_IP__
        port: 7782
    client:
      scp:
        - uri: http://__CP_IP__:7778
  metrics:
    server:
      - address: __CP_IP__
        port: 9093
