logger:
  file:
    path: /var/log/open5gs/upf.log
  level: info

upf:
  pfcp:
    server:
      - address: __UPF_IP__
  gtpu:
    server:
      - address: __UPF_IP__
  session:
    - subnet: __UE_SUBNET__
      gateway: __UE_GW__
      dnn: internet
  metrics:
    server:
      - address: 0.0.0.0
        port: 9092
