logger:
  file:
    path: /var/log/open5gs/upf.log
  level: info

upf:
  pfcp:
    server:
      - address: 10.200.100.17
  gtpu:
    server:
      - address: 10.200.100.17
  session:
    - subnet: 10.206.0.0/16
      gateway: 10.206.0.1
      dnn: internet
  metrics:
    server:
      - address: 0.0.0.0
        port: 9092
